{% set name = "archive-path" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75279003ea986a4f6748e299ba74d95e74ad75f1bd3ae02d35c125c749633a51

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit >2,<4
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - archive_path

about:
  home: https://github.com/aiidateam/archive-path
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A package to provide pathlib like access to zip & tar archives.

extra:
  recipe-maintainers:
    - chrisjsewell
    - sphuber
